---
services:
  grampsweb:
    cpus: 1.00
    mem_limit: 1g
    image: ghcr.io/gramps-project/grampsweb:26.8.0@sha256:c401ff5ec29f71c849dea9467e31821acc148eb7dda36048bc6394c840b419bd
    container_name: grampsweb
    restart: unless-stopped
    environment:
      GRAMPSWEB_TREE: "{{ gramps_tree_name }}"
      GRAMPSWEB_CELERY_CONFIG__broker_url: redis://grampsweb_redis:6379/0
      GRAMPSWEB_CELERY_CONFIG__result_backend: redis://grampsweb_redis:6379/0
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - ./users:/app/users
      - ./indexdir:/app/indexdir
      - ./thumbnail_cache:/app/thumbnail_cache
      - ./cache:/app/cache
      - ./secret:/app/secret
      - ./grampsdb:/root/.gramps/grampsdb
      - ./media:/app/media
      - ./tmp:/tmp
    networks:
      - gramps
      - newt

  grampsweb_celery:
    cpus: 1.00
    mem_limit: 768m
    image: ghcr.io/gramps-project/grampsweb:26.8.0@sha256:c401ff5ec29f71c849dea9467e31821acc148eb7dda36048bc6394c840b419bd
    container_name: grampsweb_celery
    restart: unless-stopped
    command: celery -A gramps_webapi.celery worker --loglevel=INFO --concurrency=2
    environment:
      GRAMPSWEB_TREE: "{{ gramps_tree_name }}"
      GRAMPSWEB_CELERY_CONFIG__broker_url: redis://grampsweb_redis:6379/0
      GRAMPSWEB_CELERY_CONFIG__result_backend: redis://grampsweb_redis:6379/0
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb
      - grampsweb_redis
    volumes:
      - ./users:/app/users
      - ./indexdir:/app/indexdir
      - ./thumbnail_cache:/app/thumbnail_cache
      - ./cache:/app/cache
      - ./secret:/app/secret
      - ./grampsdb:/root/.gramps/grampsdb
      - ./media:/app/media
      - ./tmp:/tmp
    networks:
      - gramps

  grampsweb_redis:
    cpus: 0.25
    mem_limit: 256m
    image: docker.io/valkey/valkey:8-alpine@sha256:cfb2aa4c8352930130fd45eb231a57310ac326d7323edae12b384b9270c46dda
    container_name: grampsweb_redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - gramps

networks:
  gramps: {}
  newt:
    external: true
