---
services:
  newt:
    image: fosrl/newt:1.10.3@sha256:41a269865ed59dc16a8412b292380b15bf506d2a3a386eca024ffb29e0d18cd5
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT={{ newt_endpoint }}
      - NEWT_ID={{ newt_client_id }}
      - NEWT_SECRET={{ newt_client_secret }}
      - DOCKER_SOCKET=unix:///var/run/docker.sock
      - DOCKER_ENFORCE_NETWORK_VALIDATION=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - newt

networks:
  newt:
    name: newt
    driver: bridge
