---
services:
  newt:
    image: fosrl/newt:1.10.2@sha256:c7b4f508cba35d698a3e4b2d55e3d902ae993d6588198291ef8e232d30421974
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT={{ newt_endpoint }}
      - NEWT_ID={{ newt_client_id }}
      - NEWT_SECRET={{ newt_client_secret }}
      - DOCKER_SOCKET=unix:///var/run/docker.sock
      - DOCKER_ENFORCE_NETWORK_VALIDATION=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - newt

networks:
  newt:
    name: newt
    driver: bridge
