---
services:
  newt:
    image: fosrl/newt:1.10.2@sha256:a8029ea7bba8496bc428868f18103453b86b1b7f08bffa934f7ba91dabc3a652
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT={{ newt_endpoint }}
      - NEWT_ID={{ newt_client_id }}
      - NEWT_SECRET={{ newt_client_secret }}
      - DOCKER_SOCKET=unix:///var/run/docker.sock
      - DOCKER_ENFORCE_NETWORK_VALIDATION=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - newt

networks:
  newt:
    name: newt
    driver: bridge
