---
services:
  backend:
    image: ghcr.io/fbuchner/meerkat-crm-backend:1.6.1@sha256:427649737d2363621b282a011ac07436181c0baafb04a39584988577cb2b2baf
    container_name: meerkat_crm_backend
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      - PUID={{ ansible_facts['user_uid'] }}
      - PGID={{ ansible_facts['user_gid'] }}
    volumes:
      - ./data:/app/data
      - ./photos:/app/static/photos
    networks:
      - meerkat_crm
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: ghcr.io/fbuchner/meerkat-crm-frontend:1.6.1@sha256:4213aa093b943afa6bc757c9c05b7f2bf55a3cca9bc949bac5b82e8e36de2148
    container_name: meerkat-frontend
    restart: unless-stopped
    networks:
      - newt
      - meerkat_crm
    depends_on:
      backend:
        condition: service_healthy

networks:
  meerkat_crm:
  newt:
    external: true
