---
services:
  backend:
    image: ghcr.io/fbuchner/meerkat-crm-backend:1.7.0@sha256:be05b8769e760ce3fbe384b3f46f180a5fc3addcd9bc01d96c1677cb0d80dbb9
    container_name: meerkat_crm_backend
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      - PUID={{ ansible_facts['user_uid'] }}
      - PGID={{ ansible_facts['user_gid'] }}
    volumes:
      - ./data:/app/data
      - ./photos:/app/static/photos
    networks:
      - meerkat_crm
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: ghcr.io/fbuchner/meerkat-crm-frontend:1.7.0@sha256:610a9a1e7605e08f1d24658c1daa9537e4d350635053cff19e2afe83dbcccfc9
    container_name: meerkat-frontend
    restart: unless-stopped
    networks:
      - newt
      - meerkat_crm
    depends_on:
      backend:
        condition: service_healthy

networks:
  meerkat_crm:
  newt:
    external: true
