---
backup_folders:
  - "immich"
  - "wiki"
  - "nextcloud"
  - "monica_v4"
  - "rss"
  - "searxng"
  - "betisier"
  - "meerkat_crm"
  - "pangolin"
  - "paperless"
  - "flip_planning"
  - "gramps"
  - "dawarich"
  - "scanopy"
  - "trek"
