---
ansible_ssh_private_key_file: "~/.ssh/keepassxc.pub"
ansible_user: sylvain

# Backup configuration (used by all hosts)
borgmatic_config_dir: "/etc/borgmatic.d"
borgmatic_encryption_mode: repokey-blake2

# Storage Box Hetzner pour les backups (remplace S3)
backup_storage_box_path: "./backup"

docker_base_path: /opt/apps

newt_endpoint: https://pangolin.sylvain.cloud

rclone_access_key_id: "{{ backup_s3_access_key }}"
rclone_secret_access_key: "{{ backup_s3_secret_key }}"
