---
services:
  crm:
    container_name: monica_v4
    image: monica:3.7.0-apache@sha256:ceb1ba4196ab2d371f504f284f4516174f4b99fe9339f2aa69a86c31d6ba414f
    env_file: .env
    volumes:
      - ./data:/var/www/html/storage
    networks:
      - newt
      - monica
    restart: unless-stopped

  monica_v4_db:
    image: lscr.io/linuxserver/mariadb:11.4.12@sha256:4fd30d278d9c85158706679451dac3d48aeec9c447fc0135d8c75b3c938b61e7
    container_name: monica_v4_db
    networks:
      - monica
    environment:
      - PUID={{ ansible_facts['user_uid'] }}
      - PGID={{ ansible_facts['user_gid'] }}
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD={{ monica_v4_db_password }}
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD={{ monica_v4_db_password }}
    volumes:
      - ./db_data:/config
    restart: unless-stopped

networks:
  monica:
  newt:
    external: true
