---
services:
  nextcloud:
    mem_limit: 1536m
    restart: unless-stopped
    image: ghcr.io/linuxserver/nextcloud:35.0.1@sha256:e2d2b2bc261e6ac0652f544b4c3db60221f9e9f78b430dfcfea46529b7e97b5b
    container_name: nextcloud
    environment:
      - PUID={{ ansible_facts['user_uid'] }}
      - PGID={{ ansible_facts['user_gid'] }}
      - TZ=Europe/Paris
      # https://github.com/linuxserver/docker-mods/tree/nextcloud-memories
      #- DOCKER_MODS=linuxserver/mods:nextcloud-memories
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      - newt
      - nextcloud

  db:
    mem_limit: 1g
    mem_reservation: 384m
    container_name: nextcloud_db
    restart: unless-stopped
    image: mariadb:lts@sha256:805c8e104bd563d5bfa24fadd3f31cd419ea859cb5277f32b5dbf2db714f9ed1
    environment:
      MYSQL_ROOT_PASSWORD: {{ nextcloud_db_password }}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: {{ nextcloud_db_password }}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - nextcloud

  cache:
    mem_limit: 256m
    restart: unless-stopped
    image: redis:bookworm@sha256:164c759a0c342ee69d08fc99219382b0fd682181465c0df2e0e6911f4c85d73c
    container_name: nextcloud_redis
    command: redis-server --requirepass {{ nextcloud_redis_password }}
    environment:
      - REDIS_PASSWORD={{ nextcloud_redis_password }}
    volumes:
      - ./redis:/data
    networks:
      - nextcloud

networks:
  nextcloud: {}
  newt:
    external: true
