---
# https://semaphoreui.com/docs/admin-guide/installation/docker
services:
  postgres:
    container_name: semaphore_postgres
    image: postgres:18@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER={{ semaphore_db_user }}
      - POSTGRES_PASSWORD={{ semaphore_db_password }}
      - POSTGRES_DB={{ semaphore_db_name }}
    volumes:
      - semaphore-postgres:/var/lib/postgresql/data
    networks:
      - semaphore-internal

  semaphore:
    container_name: semaphore
    labels:
      - pangolin.public-resources.semaphore.name=Semaphore
      - pangolin.public-resources.semaphore.full-domain={{ semaphore_domain }}
      - pangolin.public-resources.semaphore.protocol=http
      - pangolin.public-resources.semaphore.targets[0].method=http
      - pangolin.public-resources.semaphore.targets[0].port=3000
      - pangolin.public-resources.semaphore.auth.sso-enabled=true
      - pangolin.public-resources.semaphore.healthcheck.hostname=semaphore
      - pangolin.public-resources.semaphore.healthcheck.port=3000
      - pangolin.public-resources.semaphore.healthcheck.enabled=true
      - pangolin.public-resources.semaphore.healthcheck.path=/
      - pangolin.public-resources.semaphore.healthcheck.interval=30
      - pangolin.public-resources.semaphore.healthcheck.timeout=5
      - pangolin.public-resources.semaphore.healthcheck.method=GET
      - pangolin.public-resources.semaphore.healthcheck.status=200
    image: semaphoreui/semaphore:v2.17.38@sha256:6771256a64d848324f3726f07b688883fbb5dc257def079f0b16e6fb4d86e9dc
    environment:
      - SEMAPHORE_PLAYBOOK_PATH= /tmp/semaphore/
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB_HOST=postgres
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_USER={{ semaphore_db_user }}
      - SEMAPHORE_DB_PASS={{ semaphore_db_password }}
      - SEMAPHORE_DB={{ semaphore_db_name }}
      - SEMAPHORE_ADMIN_PASSWORD={{ semaphore_admin_password }}
      - SEMAPHORE_ADMIN_NAME={{ semaphore_admin_name }}
      - SEMAPHORE_ADMIN_EMAIL={{ semaphore_admin_email }}
      - SEMAPHORE_ADMIN={{ semaphore_admin }}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION={{ semaphore_access_key_encryption }}
      - TZ=Europe/Paris
    restart: unless-stopped
    #volumes:
    #  - ./requirements.txt:/etc/semaphore/requirements.txt
    depends_on:
      - postgres
    networks:
      - newt
      - semaphore-internal

networks:
  newt:
    external: true
  semaphore-internal:

volumes:
  semaphore-postgres:
