---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/sylvainmetayer/homelab
