---
services:
  scanopy-daemon:
    image: ghcr.io/scanopy/scanopy/daemon:v0.17.10@sha256:52e31171b1ae781bcff566c81b22b0ac1da1d20fc18db57aec21943827763812
    container_name: scanopy-daemon
    network_mode: host
    privileged: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SCANOPY_SERVER_URL: http://127.0.0.1:60072
    volumes:
      - ./daemon-config:/root/.config/scanopy/daemon
      - /var/run/docker.sock:/var/run/docker.sock:ro

  scanopy-postgres:
    image: docker.io/postgres:17-alpine@sha256:18cfe3ef5e6815560c98237d6216d1e5119702fb0f3894c8785dd58b8bbe5d73
    container_name: scanopy-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: scanopy
      POSTGRES_USER: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - scanopy

  scanopy-server:
    image: ghcr.io/scanopy/scanopy/server:v0.17.11@sha256:e2c1b0ae624c68ce45dfe2035a6b58c1d6614f034fbfde35ff3f3369991de73e
    container_name: scanopy-server
    restart: unless-stopped
    ports:
      - "60072:60072"
    env_file:
      - .env
    environment:
      SCANOPY_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@scanopy-postgres:5432/scanopy
      SCANOPY_WEB_EXTERNAL_PATH: /app/static
      SCANOPY_INTEGRATED_DAEMON_URL: http://host.docker.internal:60073
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      scanopy-postgres:
        condition: service_healthy
      scanopy-daemon:
        condition: service_started
    networks:
      - scanopy
      - newt

networks:
  scanopy:
  newt:
    external: true
