---
services:
  scanopy-daemon:
    image: ghcr.io/scanopy/scanopy/daemon:v0.17.11@sha256:fa393a8b1ddbc11297a0c0afc7d6b02f74032999ed2f49ec92c819b4645969db
    container_name: scanopy-daemon
    network_mode: host
    privileged: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SCANOPY_SERVER_URL: http://127.0.0.1:60072
    volumes:
      - ./daemon-config:/root/.config/scanopy/daemon
      - /var/run/docker.sock:/var/run/docker.sock:ro

  scanopy-postgres:
    image: docker.io/postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    container_name: scanopy-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: scanopy
      POSTGRES_USER: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - scanopy

  scanopy-server:
    image: ghcr.io/scanopy/scanopy/server:v0.17.11@sha256:e2c1b0ae624c68ce45dfe2035a6b58c1d6614f034fbfde35ff3f3369991de73e
    container_name: scanopy-server
    restart: unless-stopped
    ports:
      - "60072:60072"
    env_file:
      - .env
    environment:
      SCANOPY_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@scanopy-postgres:5432/scanopy
      SCANOPY_WEB_EXTERNAL_PATH: /app/static
      SCANOPY_INTEGRATED_DAEMON_URL: http://host.docker.internal:60073
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      scanopy-postgres:
        condition: service_healthy
      scanopy-daemon:
        condition: service_started
    networks:
      - scanopy
      - newt

networks:
  scanopy:
  newt:
    external: true
