---
services:
  actualbudget:
    image: docker.io/actualbudget/actual-server:26.8.0@sha256:0b300f370dba85a74998a953736a831bd931cc8cb76c0d8ceac3d3fd288dfd4d
    container_name: actualbudget
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - newt

networks:
  newt:
    external: true
