machine:
  network:
    hostname: {HOSTNAME}
    interfaces:
          - interface: eth0
            addresses:
              - "{IP}/24"
            routes:
              - network: "0.0.0.0/0"
                gateway: 192.168.1.254
                metric: 1024
            mtu: 1500
    nameservers:
        - 192.168.1.254
        - 9.9.9.9
  type: worker
  install:
    disk: "/dev/sda"
    extraKernelArgs:
      - net.ifnames=0 # to get eth0 interfaces name
#cluster:
  # TODO
  # proxy:
  #   disabled: true
  # network:
  #   cni:
  #     name: none # On installera Cilium manuellement
