FROM semaphoreui/semaphore:v2.19.10@sha256:13a3ee1ec73b2f2f8746abdd3de7fcc43814b6e4d9ba44dd3c6d70ce113e7f8a

ARG SOPS_VERSION=3.9.4
ARG AGE_VERSION=1.2.1

USER root

RUN apk add --no-cache wget && \
    wget -qO /usr/local/bin/sops \
        "https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64" && \
    chmod +x /usr/local/bin/sops && \
    wget -qO /tmp/age.tar.gz \
        "https://github.com/FiloSottile/age/releases/download/v${AGE_VERSION}/age-v${AGE_VERSION}-linux-amd64.tar.gz" && \
    tar -xzf /tmp/age.tar.gz -C /tmp && \
    mv /tmp/age/age /usr/local/bin/age && \
    mv /tmp/age/age-keygen /usr/local/bin/age-keygen && \
    rm -rf /tmp/age* && \
    apk del wget

USER semaphore
