FROM semaphoreui/semaphore:v2.18.18@sha256:c393396fba2e3b0a7b6f7e6efc9619cecb99a79f764e6fc6ea09f3421535f74e

ARG SOPS_VERSION=3.9.4
ARG AGE_VERSION=1.2.1

USER root

RUN apk add --no-cache wget && \
    wget -qO /usr/local/bin/sops \
        "https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64" && \
    chmod +x /usr/local/bin/sops && \
    wget -qO /tmp/age.tar.gz \
        "https://github.com/FiloSottile/age/releases/download/v${AGE_VERSION}/age-v${AGE_VERSION}-linux-amd64.tar.gz" && \
    tar -xzf /tmp/age.tar.gz -C /tmp && \
    mv /tmp/age/age /usr/local/bin/age && \
    mv /tmp/age/age-keygen /usr/local/bin/age-keygen && \
    rm -rf /tmp/age* && \
    apk del wget

USER semaphore
