---
services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest@sha256:4ebe6ab0297397426fe7ca015caab8f5ed3b50784cf968bfbda7887ea6b16f6e
    restart: unless-stopped
    environment:
      - SEARXNG_BASE_URL=https://{{ searxng_domain }}/
    volumes:
      - ./config:/etc/searxng:rw
    networks:
      - newt

networks:
  newt:
    external: true
