#cloud-config
users:
  - name: sylvain
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false
    passwd: ${pangolin_password}
    ssh_authorized_keys:
      - ${public_ssh_key}

ssh_pwauth: false
disable_root: true

write_files:
  - path: /opt/pangolin/config/traefik/dynamic_config.yml
    permissions: '0644'
    content: |
      http:
        middlewares:
          badger:
            plugin:
              badger:
                disableForwardAuth: true
          redirect-to-https:
            redirectScheme:
              scheme: https

        routers:
          # HTTP to HTTPS redirect router
          main-app-router-redirect:
            rule: "Host(`${pangolin_dashboard_url}`)"
            service: next-service
            entryPoints:
              - web
            middlewares:
              - redirect-to-https
              - badger

          # Next.js router (handles everything except API and WebSocket paths)
          next-router:
            rule: "Host(`${pangolin_dashboard_url}`) && !PathPrefix(`/api/v1`)"
            service: next-service
            entryPoints:
              - websecure
            middlewares:
              - badger
            tls:
              certResolver: letsencrypt

          # API router (handles /api/v1 paths)
          api-router:
            rule: "Host(`${pangolin_dashboard_url}`) && PathPrefix(`/api/v1`)"
            service: api-service
            entryPoints:
              - websecure
            middlewares:
              - badger
            tls:
              certResolver: letsencrypt

          # WebSocket router
          ws-router:
            rule: "Host(`${pangolin_dashboard_url}`)"
            service: api-service
            entryPoints:
              - websecure
            middlewares:
              - badger
            tls:
              certResolver: letsencrypt

        services:
          next-service:
            loadBalancer:
              servers:
                - url: "http://pangolin:3002"  # Next.js server

          api-service:
            loadBalancer:
              servers:
                - url: "http://pangolin:3000"  # API/WebSocket server

      tcp:
        serversTransports:
          pp-transport-v1:
            proxyProtocol:
              version: 1
          pp-transport-v2:
            proxyProtocol:
              version: 2
  - path: /opt/pangolin/config/traefik/traefik_config.yml
    content: |
      api:
        insecure: true
        dashboard: true

      providers:
        http:
          endpoint: "http://pangolin:3001/api/v1/traefik-config"
          pollInterval: "5s"
        file:
          filename: "/etc/traefik/dynamic_config.yml"

      experimental:
        plugins:
          badger:
            moduleName: "github.com/fosrl/badger"
            version: "v1.3.1"

      log:
        level: "INFO"
        format: "common"
        maxSize: 100
        maxBackups: 3
        maxAge: 3
        compress: true

      certificatesResolvers:
        letsencrypt:
          acme:
            httpChallenge:
              entryPoint: web
            email: "${le_email}"
            storage: "/letsencrypt/acme.json"
            caServer: "https://acme-v02.api.letsencrypt.org/directory"

      entryPoints:
        web:
          address: ":80"
        websecure:
          address: ":443"
          transport:
            respondingTimeouts:
              readTimeout: "30m"
          http:
            tls:
              certResolver: "letsencrypt"
            encodedCharacters:
              allowEncodedSlash: true
              allowEncodedQuestionMark: true

      serversTransport:
        insecureSkipVerify: true

      ping:
        entryPoint: "web"
    permissions: '0644'

  # Configuration Pangolin
  - path: /opt/pangolin/config/config.yml
    content: |
      gerbil:
        start_port: 51820
        base_endpoint: ${pangolin_dashboard_url}

      app:
        dashboard_url: https://${pangolin_dashboard_url}
        log_level: ${pangolin_log_level}
        telemetry:
          anonymous_usage: false

      domains:
        domain1:
          base_domain: ${pangolin_base_domain}

      server:
        secret: ${pangolin_secret}
        cors:
            origins: ["https://${pangolin_dashboard_url}"]
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            allowed_headers: ["X-CSRF-Token", "Content-Type"]
            credentials: false
        maxmind_db_path: "./config/GeoLite2-Country.mmdb"

      email:
        smtp_host: "mail.infomaniak.com"
        smtp_port: 465
        smtp_user: "${smtp_user}"
        smtp_pass: "${smtp_pass}"
        no_reply: "${smtp_user}"

      flags:
          require_email_verification: true
          disable_signup_without_invite: true
          disable_user_create_org: false
          allow_raw_resources: true
    permissions: '0600'

runcmd:
  # Log de fin de configuration
  - echo "Cloud-init configuration completed at $(date)" >> /var/log/cloud-init.log
