---
betisier_backup_enabled: true
betisier_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/betisier"
betisier_backup_encryption_passphrase: "{{ backup_passphrase }}"
