repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: cert-manager
  url: https://charts.jetstack.io
- name: cert-manager-webhook-ovh-charts
  url: https://aureq.github.io/cert-manager-webhook-ovh/
- name: synology-csi-chart
  url: https://zebernst.github.io/synology-csi-talos

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  values:
    - values/ingress-nginx.yaml
- name: cert-manager
  labels:
    module: cert-manager
  namespace: cert-manager
  chart: cert-manager/cert-manager
  createNamespace: true
  version: v1.17.0
  values:
    - values/cert-manager.yaml
- name: cert-manager-ovh
  needs:
    - cert-manager
  namespace: cert-manager
  chart: cert-manager-webhook-ovh-charts/cert-manager-webhook-ovh
  version: 0.7.3
  values:
    - values/cert-manager-ovh.yaml
- name: synology-csi
  namespace: synology-csi
  chart: synology-csi-chart/synology-csi
  version: 0.9.5-pre.1
  values:
    - values/synology-csi.yaml
