---
services:
  broker:
    container_name: paperless_redis
    image: docker.io/library/redis:8@sha256:027002f3d4161eb427643e0cc71023b582fb461c6199e699f46db843f0b39fb1
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - paperless

  db:
    container_name: paperless_db
    image: docker.io/library/postgres:18@sha256:1a5b3e745bbd82d6deb146505e504da3c2f248cac15e431951b148fbe4f8613a
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: {{ paperless_db_name }}
      POSTGRES_USER: {{ paperless_db_user }}
      POSTGRES_PASSWORD: {{ paperless_db_password }}
    networks:
      - paperless

  webserver:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PUID: {{ ansible_facts['user_uid'] }}
      PGID: {{ ansible_facts['user_gid'] }}
      TZ: Europe/Paris
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: {{ paperless_db_name }}
      PAPERLESS_DBUSER: {{ paperless_db_user }}
      PAPERLESS_DBPASS: {{ paperless_db_password }}
      PAPERLESS_SECRET_KEY: {{ paperless_secret_key }}
      PAPERLESS_URL: https://{{ paperless_domain }}
      PAPERLESS_ADMIN_USER: {{ paperless_admin_user }}
      PAPERLESS_ADMIN_PASSWORD: {{ paperless_admin_password }}
      PAPERLESS_ADMIN_MAIL: {{ paperless_admin_email }}
      PAPERLESS_OCR_LANGUAGE: {{ paperless_ocr_language }}
      PAPERLESS_TIME_ZONE: Europe/Paris
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    networks:
      - paperless
      - newt

  gotenberg:
    container_name: paperless_gotenberg
    image: docker.io/gotenberg/gotenberg:8.34@sha256:67097317623a503ba2a6a7e9ae8db6929a1f7e1bbd88077bacf2d325fbdab923
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless

  tika:
    container_name: paperless_tika
    image: docker.io/apache/tika:latest@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
    restart: unless-stopped
    networks:
      - paperless

networks:
  paperless: {}
  newt:
    external: true
