---
# Pangolin Zero Trust configuration variables

pangolin_base_domain: "sylvain.cloud"

# Pangolin Dashboard URL (without https://)
pangolin_dashboard_url: "pangolin.{{ pangolin_base_domain }}"

# Pangolin API URL (without https://)
pangolin_api_url: "pangolin-api.{{ pangolin_base_domain }}"

# Log level (debug, info, warning, error)
pangolin_log_level: "info"

# Pangolin secret (should be in secrets.sops.yaml)
pangolin_secret: "{{ pangolin_server_secret }}"

pangolin_backup_enabled: true
pangolin_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/pangolin"
pangolin_backup_encryption_passphrase: "{{ backup_passphrase }}"

security_ufw_allowed_ports:
  - { port: "22", proto: tcp }
  - { port: "80", proto: tcp }
  - { port: "443", proto: tcp }
  - { port: "51820", proto: udp }
  - { port: "21820", proto: udp }
