---
- name: Configure shared runtime for app LXCs
  hosts: proxmox_apps
  pre_tasks:
    # WARNING : You cannot override variables with this, make sure variable is not defined before.
    # Export your age key in environment
    # https://github.com/mozilla/sops/issues/933#issuecomment-1081228720
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: geerlingguy.docker
      become: true
      tags: setup
    - role: docker_service
      tags: setup
    - role: borgmatic
      tags: backup,setup

- name: Configure echo app LXC
  hosts: echo
  pre_tasks:
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: echo
      tags: echo,app

- name: Configure rss app LXC
  hosts: rss
  pre_tasks:
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: rss
      tags: rss,app

- name: Configure betisier app LXC
  hosts: betisier
  pre_tasks:
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: betisier
      tags: betisier,app

- name: Configure monica_v4 app LXC
  hosts: monica_v4
  pre_tasks:
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: monica_v4
      tags: monica,app

- name: Configure wiki app LXC
  hosts: wiki
  pre_tasks:
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: wiki
      tags: wiki,app

- name: Configure nextcloud app LXC
  hosts: nextcloud
  pre_tasks:
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: nextcloud
      tags: nextcloud,app

- name: Configure semaphore app LXC
  hosts: semaphore
  pre_tasks:
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: semaphore
      tags: semaphore,app

- name: Configure meerkat_crm app LXC
  hosts: meerkat_crm
  pre_tasks:
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

  roles:
    - role: meerkat_crm
      tags: meerkat_crm,app
