---
newt_client_id: "{{ newt_docker_client_id }}"
newt_client_secret: "{{ newt_docker_client_secret }}"

rss_backup_enabled: true
rss_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/rss"
rss_backup_encryption_passphrase: "{{ backup_passphrase }}"

betisier_backup_enabled: true
betisier_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/betisier"
betisier_backup_encryption_passphrase: "{{ backup_passphrase }}"

monica_v4_backup_enabled: true
monica_v4_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/monica_v4"
monica_v4_backup_encryption_passphrase: "{{ backup_passphrase }}"

wiki_domain: "wiki.sylvain.cloud"
wiki_backup_enabled: true
wiki_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/wiki"
wiki_backup_borgmatic_password: "{{ backup_passphrase }}"

nextcloud_backup_enabled: true
nextcloud_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/nextcloud"
nextcloud_backup_borgmatic_password: "{{ backup_passphrase }}"

semaphore_backup_enabled: true
semaphore_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/semaphore"
semaphore_backup_encryption_passphrase: "{{ backup_passphrase }}"
