---
nextcloud_backup_enabled: true
nextcloud_backup_borgmatic_target: "ssh://{{ backup_storage_box_username }}@{{ backup_storage_box_hostname }}/{{ backup_storage_box_path }}/nextcloud"
nextcloud_backup_borgmatic_password: "{{ backup_passphrase }}"
