---
services:
  betisier:
    container_name: betisier
    networks:
      - newt
      - betisier
    image: ghcr.io/sylvainmetayer/betisier-tp:latest@sha256:083bdcae175dbbe2d131d0b1fd60ff4d77004f124c671033db478a90e542ad00
    environment:
      - PUID={{ ansible_facts['user_uid'] }}
      - PGID={{ ansible_facts['user_gid'] }}
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
    restart: unless-stopped

  betisier_db:
    networks:
      - betisier
    image: lscr.io/linuxserver/mariadb:11.4.12@sha256:4fd30d278d9c85158706679451dac3d48aeec9c447fc0135d8c75b3c938b61e7
    container_name: betisier_db
    environment:
      - PUID={{ ansible_facts['user_uid'] }}
      - PGID={{ ansible_facts['user_gid'] }}
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD={{ betisier_db_password }}
      - MYSQL_DATABASE=betisier
      - MYSQL_USER=betisier
      - MYSQL_PASSWORD={{ betisier_db_password }}
    volumes:
      # No DB volume, since we want to reset database on restart
      - ./dump.sql:/config/initdb.d/betisier.sql:ro
    restart: unless-stopped

networks:
  betisier:
  newt:
    external: true
